import "@/styles/globals.css";
// import { getMenu } from "@/app/data";
import Link from "next/link";
import { Header } from "@/components/Header";

export const metadata = {
  title: "Sanity Template",
  description: "Generated by Next + Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const menuData = await getMenu();
  // console.log(menuData);
  return (
    <html lang="en">
      <body>
        {/* <Header menuData={menuData} /> */}
        <main className="">{children}</main>
      </body>
    </html>
  );
}
