import "@/styles/globals.css";
import Link from "next/link";

export const metadata = {
  title: "My Awesome Site",
  description: "Generated by Next + Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <header className=""></header>
        <main className="">{children}</main>
      </body>
    </html>
  );
}
