import "@/styles/globals.css";
import { getLayout } from "@/lib/sanity";
import Link from "next/link";
import { Header } from "@/components/Header";

export const metadata = {
  title: "Sanity Template",
  description: "Generated by Next + Sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const layout = await getLayout();
  console.log(layout.menuLinks);
  return (
    <html lang="en">
      <body>
        <Header menuLinks={layout.menuLinks} />
        <main className="">{children}</main>
      </body>
    </html>
  );
}
